.github/workflows/publish_server.yml
This PR is a follow-up for #66 
It builds published the docker image to the ghrc registry
=> Add CI for publishing docker image on ghrc

.gitignore, README.md, snap/snapcraft.yaml
Adds a snap build configuration with at least some of the right interface requirements that will be needed.
Based on (very) cursory testing of the following kind, Works On My Machine:
```bash
❯ hwctl
NotSeen(
NotSeenResponse {
status: "Not Seen",
},
)
```
=> Adds a starter for a snapcraft.yaml

README.md, client/README.md, client/hwlib/src/lib.rs, client/hwlib/src/py_bindings.rs, client/hwlib/tests/test_cert_status.rs, client/hwlib/tox.ini
This PR just removed the top-key like "Certified" or "Not seen" from the client response and outputs the value itself
So, instead of having `{'NotSeen':{'status':'Not Seen'}}`, we just get `{'status':'Not Seen'}`
The tests for both client and python bindings were updated as well
=> Fix: remove top key from the hwlib response body

Cargo.lock, client/README.md, client/hwctl/Cargo.toml, client/hwlib/Cargo.toml, scripts/update_package_version.py
This PR just fixes the string format that we add to the debian/changelog file and fixes typos in readme
It also sets the package version to match the one on the LP (0.1.0 instead of 0.0.1)
=> Fix update_package_version script

server/hwapi/external/c3/client.py, server/hwapi/external/c3/helpers.py
This PR adds the progress bar to be printed while data is loaded from C3 to make it more user-friendly.
Here is an example of how it looks:
=> Add progress bar for C3 importing module

.github/workflows/publish_server.yml
Not sure if we want this just yet, but it might be good to start testing it and I don't see a downside to doing it now. This will periodically rebuild the hardware-api OCI image and charm on a schedule (weekly for now, can increase later easily if we want).  When rebuilding it, we should also get the latest c3 data in the sqlite db
=> Rebuild the OCI and Charm periodically

.github/workflows/test_hwlib_debian_build.yaml, client/README.md, client/hwlib/debian/changelog, client/hwlib/debian/control, client/hwlib/debian/copyright, client/hwlib/debian/watch
This PR fixes the warnings generated by `lintian`, which is a required stage before creating the MIR bug (see more: https://github.com/canonical/ubuntu-mir?tab=readme-ov-file#main-inclusion-requirements)
It also updates the CI job to include the lintian check.
Also, as it was recommended in the [~hardware-api MM thread](https://chat.canonical.com/canonical/pl/sxnnnndodinqfkdcrco6sb8y7a), the version has been changed to `0.0.1~ppa1` (and updated to `~ppa2`) to preserve the “clean” version for publishing it to the archive after getting approval
=> Fix lintian errors and update package version

.github/workflows/test_hwlib_debian_build.yaml, client/README.md, client/hwlib/debian/changelog, client/hwlib/debian/vendor-rust.sh
This PR updates the changelog, CI job, and readme to use oracular distro instead of focal.
The current PPA where the lib is published will be wiped up, so that's why the changelog is modified instead of being updates
For noble, jammy, and focal, we'll use backporting. Here you can see an example of how I've tested it in a test PPA: https://launchpad.net/~nhutsko/+archive/ubuntu/ppa/+packages?field.name_filter=rust&field.status_filter=published&field.series_filter=
Also, I've updated the `vendor_rust.sh` script to exclude the shell scripts from the `vendor/vcpkg` libraries. We don't use these scripts in our code and don't depend on it, but they generate lintian errors because of the incorrect bash syntax
=> Update changelog and related files to publishing for oracular

server/hwapi/data_models/repository.py, server/hwapi/endpoints/certification/logic.py, server/hwapi/endpoints/certification/request_validators.py, server/hwapi/endpoints/certification/response_builders.py, server/hwapi/endpoints/certification/response_validators.py, server/poetry.lock, server/pyproject.toml, server/schemas/openapi.yaml, server/tests/data_generator.py, server/tests/endpoints/certification/test_certification.py
Since some devices don't have bios (like Raspberry Pi) and we store the value for Bios field in C3 as None, here we allow the bios field to be optional
It means that the bios field can be specified as None in certification requests and responses.
=> Allow bios field to be optional

server/hwapi/external/c3/client.py, server/hwapi/external/c3/helpers.py, server/tests/external/c3/test_client.py
It turned out that C3 cannot handle so many frequent requests in a row and starts returning 500 error, I've decided to drop the threading solution and revert the script logic
Also, to avoid printing the progress bar with the same output multiple times, I've updated the script to print it only when the percentage changes, and change it to print only one digit after the decimal point.
=> Drop threading in the c3 client logic

.github/workflows/publish_server.yml
This PR simply increases the timeout for the publish_server job to 10 hours instead of the default 6 hours
I've used this checkbox job as a reference: https://github.com/canonical/checkbox/blob/main/.github/workflows/deb-daily-builds.yml#L18
=> Update timeout for publish_server action

server/hwapi/external/c3/helpers.py
Currently, we use `end='\r'` at the end of the print statement when printing progress bar during importing data from C3
However, it doesn't behave as expected in GH actions:
I've found out that replacing it with `end=""` can help: https://github.com/jupyterlab/jupyterlab/issues/5326#issuecomment-442029859 (I hope it'll work for GH actions as well, because this approach is recommended for other tools)
=> Remove \r sign at the print end in progress bar

server/hwapi/data_models/repository.py, server/hwapi/endpoints/certification/certification.py, server/hwapi/endpoints/certification/logic.py, server/hwapi/endpoints/certification/response_validators.py, server/hwapi/external/c3/client.py, server/poetry.lock, server/schemas/openapi.yaml, server/tests/data_generator.py, server/tests/endpoints/certification/test_certification.py
This PR updates the server logic after testing it on certified machines using scripts in #234. The patches contain the following fixes:
* Use a list of BIOSes instead of `first()`. Since we match only bios vendor and version, there might be multiple BIOSes with different revisions but the same version. One of them may belong to the matching machine. So, now we use all matching BIOSes instead of getting the first one. Additionally, we don't match other fields like `revision` since firmware may receive revision updates pretty frequently, but it still allows us to consider hardware as potentially certified since we're still working with the same BIOS version
* Checking the board version turned out to be a strict validation. After the discussion with the team, it was decided to check only the …
=> Improve server logic

client/README.md, client/debian/control
This PR specifies `cargo` version in `debian/control` to be at least `1.75`, so auto-package tests pass for all the supported distributions.
It also updates the instructions on how to run these tests locally
=> Specify cargo version deb pack

client/debian/changelog, client/hwctl/src/main.rs
Since a user is interested only in the status information, we should avoid outputting the request information.
=> In hwctl command, don't output the request information

.github/workflows/test_hwlib_debian_build.yaml, client/README.md, client/debian/changelog, client/debian/control
Since currently the upcoming release is Questing, the main branch has to support it. The PR updates all the builds and instructions to be for Questing instead of Plucky
The changes (both `sbuild` and `autopkgtests` in VM) were tested locally
=> Package the project for questing

client/hwlib/src/collectors/cpuinfo.rs, client/hwlib/src/collectors/hardware_info.rs, client/hwlib/src/collectors/os_info.rs
Fixes #313 
This PR adds more context for places where we try to read from a file or execute it. If such a file is not found, we provide which file has not been found (it used to be just `File not found` error with no information which file)
This is how it looks when an executable binary is not found
```bash
$ sudo mv /usr/bin/lsb_release ./
$ sudo ./target/debug/hwctl
ERROR: cannot collect system data
Caused by:
0: Failed to get release info using lsb_release -c
1: No such file or directory (os error 2)
```
Example when SMBIOS data is not available
```
ERROR: cannot collect system data
Caused by:
0: Failed to load SMBIOS entry point 64 from: /sys/firmware/dmi/tables/smbios_entry_point
1: Permission denied (os error 13)
```
=> Add better error handling for file not found errors

.github/workflows/publish_server.yaml, .github/workflows/run_integration_tests.yaml, .github/workflows/test_server.yaml
Since the runners are getting moved to PS7, we need to change the setup and use the `DOCKERHUB_MIRROR` environment variable provided by a runner. The default value is specified in case a job gets picked up by a PS6 runner, which may not provide such variable
UPD: The usage of the mirror has been dropped.
=> Remove the usage of docker mirror in CI

.github/workflows/publish_server.yaml
This PR adds the missing step in the `publish_server.yaml` action to set up docker build.
Without is the following error occurs:
```
Run docker/build-push-action@v6
GitHub Actions runtime token ACs
Docker info
Proxy configuration
Error: Docker buildx is required. See https://github.com/docker/setup-buildx-action to set up build.
```
=> Add docker-buildx step to the publish_server action

client/debian/usr.bin.hwctl
Fixes #319 and [C3-1133](https://warthogs.atlassian.net/browse/C3-1133)
Updates the AppArmor profile to fix denials that occur while the binary is executed in LXC.
[C3-1133]: https://warthogs.atlassian.net/browse/C3-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update AppArmor profile to fix execution in lxc

.github/workflows/openapi_gh_pages.yaml, .github/workflows/package_client.yaml, .github/workflows/publish_server.yaml, .github/workflows/run_integration_tests.yaml, .github/workflows/test_client.yaml, .github/workflows/test_hwlib_debian_build.yaml, .github/workflows/test_server.yaml, .github/workflows/validate_workflows.yaml
This PR adds [`zizmor`](https://docs.zizmor.sh/) validation to the workflows for security checks.
The following changes are most relevant:
- Pinning non-`actions/*` actions to a commit SHA with version comment
- Replacing `actions-rs/toolchain` actions with `dtolnay/rust-toolchain` (`actions-rs` is [unmaintained/deprecated](https://github.com/actions-rs/toolchain/issues/216))
=> Add workflow validation

client/snapcraft.yaml
Related to #336.
SnapD may not support manpages yet, but we might as well dump it in there for now...
=> feat(client): Dump manpage into the snap

server/hwapi/data_models/repository.py, server/tests/data_generator.py, server/tests/endpoints/certification/test_certification.py
Turned out that sometimes motherboard is classified as `SYSTEM` device (for example here: https://ubuntu.com/certified/202006-27980)
The server matching logic is being updated here to handle this case.
=> Match system category when looking for motherboard

.github/workflows/publish_server.yaml
The PR adds the lacking permissions so the job can create tags and releases
=> Allow build-and-push-charm step to create releases

.github/workflows/publish_client_crates.yaml
This PR adds a GitHub Actions workflow to automatically publish the hwlib crate to crates.io when a new `v*.*.*` tag is pushed.
* Runs only on version tags (e.g. `v0.9.1`)
* Verifies tag matches client/Cargo.toml version
* Publishes hwlib using cargo publish with lockfile enforcement
`hwctl` cannot be published now due to the following error:
```
$ cargo publish -p hwctl
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `hwlib` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
Since the CLI tool can be installed as deb or snap and the client consumers will need the library as a crate, we can just publish the lib …
=> Add CI to publish hwlib when a tag gets created
